appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 6B5lZSpnzx8LA9cSW7hXTASwmQ+ha2haUacd1Wyr0nqiC/iE5K25Pi4gJwjPzh7bCLDOIUyTcuRQTFIB2Gg6pTPmNhVE5RmrZb+4IfHpjOwV9KtXczINgELLLhAhFt04c17dJJqGAzLbNp/DDJJ5Srzo1+pEpwXJIV7jv3VfREAJ95jcVigdoFX0sQqnQflz9WpOnwySuXNf7Hn8TH0baJW5k7+usy56v1VEShJU32slMgVx/tBqg3LBnQJpmN6JedCBYDq6liyORBshG0pejI/xcgyVdk2JJ9blFlkAEkiOm2s+I1xhFpLd9OY6L/MDjLPUDQuQIJmb7912wG8ypxo38Mw8wXV9gf45GHLo6h/TPhgXAM7oDPh1kFzaIzT3ojOqYTIH4frsmr10v8LiiWqxRNrHEax8+geoZbFFmkInmA+uzZNGz8SM3xP9RePBPD1lYL3DYBl4/aru6bm+Ndw8pb+TPyHobV5Jcs2PYN/OYyMq+2LVxELgEOWTUrTeLqnyuBLzY5VpjD3+D2gX7/4/6ho+XLVxaRDIZP2lXVGx8nPxiyIon/BQbW5AQinjZraQp8iFN/MC+AICm5XwWQ30Tfh4R51GGQoFbENk3IUVSXU70UW91JrzFrMiZTIXmijOnyqXioIE+yaenaNcHGziO9HHYCtv8LQfDaKRhyM=}
